DESCRIBE student;
ALTER TABLE student ADD FOREIGN KEY(department) REFERENCES faculty(department);
-- ALTER TABLE student ADD building_name varchar(40);
DESCRIBE course;
alter table student ADD department varchar(45);
alter table iiitdm add foreign key(building_name) references building(building_name);
describe iiitdm;
describe FACULTY;
insert into course VALUES(1000,'PSP','CSE');
insert into course VALUES(1001,'PSPP','CSE');
insert into course VALUES(1004,'DSA','CSE');
insert into course VALUES(1006,'DSAP','CSE');
insert into course VALUES(1005,'DSCS','CSE');
SELECT * from faculty;
insert into faculty VALUES(1,'A','CSE','PSP');
insert into faculty VALUES(5,'E','CSE','LA');
ALTER TABLE FACULTY CHANGE subject subject_name varchar(45);
insert into faculty(faculty_name,department,subject_name) values('D','CSE','DSCS');
update faculty set faculty_name='C' where faculty_name='c';
select * from iiitdm;
describe student;
select * from course;
describe building;
ALTER TABLE building DROP COLUMN floor; 
INSERT INTO building VALUES('Ashoka',2,1);
select * from building;
select * from student;
INSERT INTO student(student_name,department,course,building_name) VALUES('A','CSE','PSP','Ashoka');
INSERT INTO student(student_name,department,course,building_name) VALUES('B','CSE','PSPP','Ashoka');
INSERT INTO student(student_name,department,course,building_name) VALUES('C','CSE','STD','Ashoka');
INSERT INTO student(student_name,department,course,building_name) VALUES('D','CSE','PSP','Ashoka');
INSERT INTO student(student_name,department,course,building_name) VALUES('E','CSE','DSA','Ashoka');
ALTER TABLE building ADD column floor int;
UPDATE building SET floor=1 WHERE room_no=1;
INSERT INTO building VALUES('Ashwatha',3,1);
SHOW INDEX FROM student;
alter TABLE student DROP INDEX course_UNIQUE;

-- IIITDM insertion
describe iiitdm;
select * from faculty;
INSERT INTO iiitdm values('A',1,'Ashoka');
insert into iiitdm values('B',3,'Ashwatha');
INSERT INTO iiitdm VALUES ('C',5,),('D',6,),('E',7);
